== The scope of this secure development project

This project is developing the software and hardware for an IoT device that is installed on customer OT networks. The IoT device connects to a cloud data platform, which provides reports to the users.

== Project security objectives & scope
 
Primary security goal: Launch the beta version with core authentication features. Prepare for EU CRA.

Out of scope (currently): Certifications.

You can see a summary of the scoping of internal controls in {{#report}}"name": "secdeva/reports/xref", "identifier": "secdeva_register_internal-controls"{{/report}}.
 
== Target audience & stakeholders
The following stakeholders will use this product and/or care about its security.
 
End users:

* Customer OT staff

Internal stakeholders: 

* Service engieners
* Quality and compliance
* CTO

NOTE: Set the owner field of this card to denote the person, who is responsible for cybersecurity of this development project. 

== Success metrics (KPIs)
How will we measure if the security integration was successful?

The built-in progress metrics in this tool will be used, first on adoption step 1, and later on adoption step 2.

== Milestones and checkpoints

.Instructions
[%collapsible]
=====
[TIP]
====
It is recommended to have 2–6 checkpoints per year to keep secure development work on track. You can integrate secure development checkpoints into practices you already have, such as:

* Program increment reviews
* Quarterly reviews
* Milestone reviews
* Gate reviews

====
=====

A periodic cybersecurity review is organizes 4 times a year, aligned with program increment reviews.

== Activation

Once you have filled in this template, use the "Activate" workflow transition to mark this card ready.